services:
  - type: web
    name: smartdocs
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: INSTAGRAM_USERNAME
        sync: false
      - key: INSTAGRAM_PASSWORD
        sync: false
